openapi: 3.0.0
info:
  description: Vending machine API definition
  version: "1.0.0"
  title: Vending machine API
  contact:
    email: manel@abacum.io
paths:
  /wallet:
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                new_balance:
                  type: number
                customer_name:
                  type: string
      responses:
        204:
          description: No content
  /order:
    post:
      summary: Place an order to the vending machine
      description: Place an order to the vending machine
      responses:
        200:
          description: Successfull order
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderResponse"

      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
  /customers:
    post:
      summary: Create or return a customer
      description: Adds or retrieve user with the amount of credit remaining
      responses:
        200:
          description: A Customer object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignIn"
        description: Allow or not user access to vending machine
  /products:
    get:
      summary: Get the list of products to show
      responses:
        200:
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      quantity:
                        type: number
                      product:
                        $ref: "#/components/schemas/Product"
components:
  schemas:
    Product:
      type: object
      required: ["id", "name", "price", "stock"]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: Coca-cola
        price:
          type: number
          example: 2.5
        stock:
          type: integer
          example: 15
        image:
          type: string

    OrderResponse:
      type: object
      properties:
        new_balance:
          type: number
          example: 0.33
    Order:
      type: object
      properties:
        customer_name:
          type: string
          example: Jairo
        slot:
          type: string
          format: uuid
    SignIn:
      type: object
      required:
        - customer_name
      properties:
        customer_name:
          type: string
          example: Jairo
    Customer:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: Jairo
        credit:
          type: number
          example: 2.00
        created_at:
          type: string
          format: date-time
        last_login:
          type: string
          format: date-time
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/MANELET_1/vending-machine/1.0.0
