# Generated by Django 4.2.2 on 2023-09-04 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vending", "0003_product_updated_at"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VendingMachineSlot",
            new_name="Slot",
        ),
        migrations.AlterModelTable(
            name="slot",
            table="slot",
        ),
    ]
