# Generated by Django 4.2.2 on 2023-09-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vending", "0004_rename_vendingmachineslot_slot_alter_slot_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "name",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("credit", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "customer",
            },
        ),
    ]
