# Generated by Django 4.2.2 on 2023-09-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vending", "0005_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="credit",
            field=models.FloatField(default=0),
        ),
    ]
