# Generated by Django 4.2.2 on 2023-09-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vending", "0006_alter_customer_credit"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
